name: WakaTime status update

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    - cron: "1 0 * * *"

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          # WakaTime API key stored in secrets, do not directly paste it here
          WAKATIME_API_KEY: "waka_492de44f-3cb2-425a-92cd-ec9175dc10c5"
          # Automatic github token
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: "main"
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
          STATS_RANGE: "last_7_days"
