name: WakaTime status update

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    - cron: "1 0 * * *"

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          GITHUB_TOKEN: ${{ github.token }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BRANCH: "main"
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
          STATS_RANGE: "last_7_days"
